### ISSUE TITLE
[haxsite] Single-site mode for hax (php)

### ISSUE THREAD

**Issue by TaylorJadin** [haxtheweb/issues#1608]
I'd love to see HAX have a "single site mode." This would be an option to allow one public site to live at a nice clean URL like hax.mydomain.com without having to copy or symlink files outside the normal directory hax lives in.

I could see something like this as either an option you could enable post-install, or (if it would be easier to implement) as a separate release that has its own folder structure. To log in, you have to visit hax.mydomain.com/hax-admin or something. I'm sure there is more than one way to do this!

**Comment by btopro** [comment]
Thank you for adding this. Once we add support for logging into sites that your anonymous on this will be 1 step closer. I agree that's a good idea to have the capability to start from a peeled off site instead of having to download / peel a space off. HAX11ty is not a multi-site, it's a stand alone site that uses 11ty + the HAX theme engine / component library https://github.com/elmsln/hax11ty as 1 such option that we use for publishing some stand alone sites in our library

**Comment by btopro** [comment]
#2008 now supports single site production and publishing via CLI.
#1893 needs to be backported and then this can be deployed stand alone
#2043 will ensure we can maintain all derivatives of the platform

**Comment by btopro** [comment]
#1893 dup here; node has this now
