### ISSUE TITLE
[HAXdesktop] File submenu items should read/write HAX sites from/to hard drive

### ISSUE THREAD

**Issue by whatsacomputertho** [haxtheweb/issues#686]
This would involve...
- Going into the main.js file within the HAXdesktop repo
- Adding some lines of code within the click function for the submenu items labeled "Open" and "Save".
- Possibly consider the fact that there is no variable in the script tracking the currently "Opened" directory; might need to be added
- Update the comments I left related to this issue also

**Comment by btopro** [comment]
try wiring a button up to effectively copy the files from the different boilerplates - https://github.com/elmsln/HAXcms/tree/master/system/boilerplate

to make a new site then the files under `site` are cloned and then some templating syntax applied. The site.json is really the only thing that actually changes per site since it's headless and driving everything.

The NodeJS version of this script is here / would be worked on here as part of the route:
https://github.com/elmsln/HAXcms/blob/master/system/backend/nodejs/routes/createSite.js


Can see the PHP version of this function here: https://github.com/elmsln/HAXcms/blob/master/system/backend/php/lib/Operations.php#L1659

**Comment by btopro** [comment]
duplicate
